improve failure reporting on vuln scans

diff --git a/cloudbuild_CI.yaml b/cloudbuild_CI.yaml
--- a/cloudbuild_CI.yaml
+++ b/cloudbuild_CI.yaml
@@ -45,9 +45,10 @@ steps:
     args:
     - -c
     - |
+      echo 'Scan ID:' $(cat /workspace/scan_id.txt)
       gcloud artifacts docker images list-vulnerabilities $(cat /workspace/scan_id.txt) \
       --format='value(vulnerability.effectiveSeverity)' | if grep -Fxq CRITICAL; \
-      then echo 'Failed vulnerability check' && exit 1; else exit 0; fi
+      then echo 'Failed vulnerability check - CRITICAL vulnerabilities found' && exit 1; else exit 0; fi
     id: 'severity-check-gcp-variant-transforms-docker'
     waitFor: ['scan-gcp-variant-transforms-docker']
 
@@ -78,16 +79,19 @@ steps:
       gcloud artifacts docker images scan gcr.io/${PROJECT_ID}/gcp-variant-transforms:${COMMIT_SHA} \
       --format='value(response.scan)' > /workspace/scan_id.txt
     id: 'scan-gcp-variant-transforms-custom-runner-docker'
+    waitFor: ['build-variant-transforms-custom-runner-docker']
 
   - name: gcr.io/cloud-builders/gcloud
     entrypoint: '/bin/bash'
     args:
     - -c
     - |
+      echo 'Scan ID:' $(cat /workspace/scan_id.txt)
       gcloud artifacts docker images list-vulnerabilities $(cat /workspace/scan_id.txt) \
       --format='value(vulnerability.effectiveSeverity)' | if grep -Fxq CRITICAL; \
-      then echo 'Failed vulnerability check' && exit 1; else exit 0; fi
+      then echo 'Failed vulnerability check - CRITICAL vulnerabilities found' && exit 1; else exit 0; fi
     id: 'severity-check-gcp-variant-transforms-custom-runner-docker'
+    waitFor: ['scan-gcp-variant-transforms-custom-runner-docker']
 
   - name: 'gcr.io/cloud-builders/docker'
     args:
